version: '3.3'

services:
  spacemate-scanner:
    image: spacemate-scanner
    container_name: spacemate-scanner
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:3000:3000
    restart: always
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '4G'